### ISSUE TITLE
Apply the model into a new dataset

### ISSUE THREAD

**Issue by ChocoWu** [CyberAgentAILab/layout-dm#1]
Hi, Thank you for your excellent work.

I want to apply this method to a new dataset, such as a Visual Genome. But I note that only the pre-processed data is provided. So, I do not know how to pre-process the new dataset so as to run the model correctly. Could you please provide some notes about how to pre-process the data, like the description of the structure of the input data, or some steps?

**Comment by naoto0804** [comment]
I appreciate your interest! 
Please refer to [this doc](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md) and follow the instructions.
If you are still not sure about something, please let me know.

**Comment by SchumannTian** [comment]
thank you for the instructions!
I found some file may lost in [this doc](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md)， like [src/trainer/trainer/base.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/base.py) and [preprocess](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/base.py#L67)

**Comment by SchumannTian** [comment]
> I appreciate your interest! Please refer to [this doc](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md) and follow the instructions. If you are still not sure about something, please let me know.

thank you for the instructions!
I found some file may lost in [this doc](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md)， like [src/trainer/trainer/base.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/base.py), [preprocess](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/base.py#L67) and [src/trainer/trainer/rico.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/rico.py)

**Comment by naoto0804** [comment]
> I found some files may be lost

Thank you for pointing that out! I have fixed the relative path, so it should be OK now.

**Comment by ChocoWu** [comment]
> > I appreciate your interest! Please refer to [this doc](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md) and follow the instructions. If you are still not sure about something, please let me know.
> 
> thank you for the instructions! I found some file may lost in [this doc](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md)， like [src/trainer/trainer/base.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/base.py), [preprocess](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/base.py#L67) and [src/trainer/trainer/rico.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/rico.py)

I guess there are some mistakes in the [this doc](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md). If I am right, the [base.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/base.py) should be in [src/trainer/trainer/datasets/base.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/datasets/base.py), and also for [src/trainer/trainer/datasets/rico.py](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/src/trainer/trainer/datasets/base.py). Besides, there is no directory about [preprocess](). The [clustering_coordinates.py]() is in the [bin](https://github.com/CyberAgentAILab/layout-dm/blob/main/bin) directory.

**Comment by naoto0804** [comment]
@ChocoWu Thank you for pointing this out. I updated the doc again.
