### ISSUE TITLE
how we get x_0 from x_T when training if 't' is an arbitrary integer number between T and 0

### ISSUE THREAD

**Issue by WuChannn** [CyberAgentAILab/layout-dm#10]
An issue following [#9 ]

1. when training, there is no code needs [x_0 from x_T](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/models/categorical_diffusion/base.py#L293), so I am confused how we get x_0 from x_T when training if 't' is an arbitrary integer number between T and 0.
2. why randomly sampled a 't' between 0 to T for every item in a batch? we only need to know the specific xt and xt-1, not the loop from 0 to T?

Looking forward to your reply.

**Comment by naoto0804** [comment]
Please go back to #9 since the topic is identically the same (I have re-opened #9)
