### ISSUE TITLE
environment configuration issues

### ISSUE THREAD

**Issue by Lanjiong-Li** [CyberAgentAILab/layout-dm#12]
I do follow the readme.md to set up the requirements, but I found that you mention **pytorch1.12+cuda11.3** is necessary, while the **poetry install** command install all the dependencies through the pyproject.toml, where I found the torch version is 1.10.2, therefore leads to some problems about PyG version.
So i would like to confirm the exact version, thanks a lot!

**Comment by naoto0804** [comment]
Hi, thank you for visiting our repo.
Pytorch 1.12 in README must be a typo, thank you for pointing it out.

**Comment by naoto0804** [comment]
fixed (9cf122d).
