### ISSUE TITLE
How to compute FID score with the trained fid_model?

### ISSUE THREAD

**Issue by ZetangForward** [CyberAgentAILab/layout-dm#19]
Hi, I find you have trained one fid model, but how to use this trained fid model to compute FID score? Can you provide the running scripts? thanks.

**Comment by naoto0804** [comment]
For example, please refer to [this part of the evaluation](https://github.com/CyberAgentAILab/layout-dm/blob/main/eval.py#L146-L148)

**Comment by ZetangForward** [comment]
Thanks for your kindly reply!
