### ISSUE TITLE
About training log

### ISSUE THREAD

**Issue by lifengheng** [CyberAgentAILab/layout-dm#20]
Hi, thanks for your great work. 
I follow the instructions in custom_dataset.md to train layoutDM on custom dataset, but I find the loss is high when the training is over. The loss descends from 15 to 12 after 20 epoches and fluctuates between 13 and 12 in the next 30 epoches.  Is this normal, Could you share the training log ? Thanks a lot.

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our work!
Sorry, I didn't have the exact log, but it decreases steadily at the beginning and converges. I'm not sure whether the values are typical; 
Maybe the better way is to compute FID regularly during training.

**Comment by lifengheng** [comment]
Thanks for your quick reply.
I will check FID during training.
