### ISSUE TITLE
customize condition

### ISSUE THREAD

**Issue by kietna1809** [CyberAgentAILab/layout-dm#21]
Do you have any guide to generate new layout based on customize condition. I am trying generate layout by parsing my own condition to LayoutDM but don't know where to start. As far as my research the condition fit to model are been extracted from Publaynet and Rico dataset. 
Another question is "Can the model generate layout by using combination of multiple condition, for instance generate layout using both relation + cwh condition"
Cheer thanks

**Comment by naoto0804** [comment]
> Do you have any guide to generate new layout based on customize condition

We've defined some common use-cases as "task" [here](https://github.com/CyberAgentAILab/layout-dm/blob/e107db0a84ed83876ecfd257149a99229f662176/src/trainer/trainer/helpers/task.py#L16-L24). If these cases do not meet your requirements, then you can define your task and implement [get_cond](https://github.com/CyberAgentAILab/layout-dm/blob/e107db0a84ed83876ecfd257149a99229f662176/src/trainer/trainer/helpers/task.py#L94-L106) for that task by hiding all the fields that you want to predict.

> using both relation + cwh condition

It's possible. Relation information is enforced [here](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/models/categorical_diffusion/base.py#L260-L269).
