### ISSUE TITLE
some problems about generating after training

### ISSUE THREAD

**Issue by Lanjiong-Li** [CyberAgentAILab/layout-dm#22]
Following the guide I successfully train a layoutdm model based on my own dataset, I then use demo.ipynb to test my own layoutdm model.
But I found that it seems like I can only get a result by providing one of the layout from my dataset as one of the inputs, I am not sure if I get this right or not.From my perspective, it exact info from the layout I provide, like its mask, label, bbox, and then I can choose cond such as 'c', and layoutdm will then choose some of the categories from the info he exacted before and generate a layout for me.
If this is really the way it works, then can I just directly tell layoutdm the categories and their number I want and give me a layout?Where can I directly type in the categories I want if I using 'c' condition?
(cause I only see `tokenizer = LayoutSequenceTokenizer(data_cfg=data_cfg, dataset_cfg=dataset_cfg)` to define the final inputs, and it is for coverting a layout into a sequence)

**Comment by naoto0804** [comment]
If I understand correctly, your question is, "Is it possible to directly feed the known conditions without referring to a real sample?". It is indeed possible. Please refer to [this instruction](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md#testing-on-custom-dataset)

**Comment by Lanjiong-Li** [comment]
It is this your previous respond？

> You might further look at [get_cond](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/helpers/task.py#L27-L151). GIven a batch size B and token length S, what you only have to do is instantiating two variables, "seq" and "mask".

I think this may solve my problem, thanks with that, I will try this.

As for [the instruction](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md#testing-on-custom-dataset), the input is still a given layout, isn't it? I am actually mean to just input some categories(labels) which the model has learned before, instead of a known layout(bbox).

**Comment by naoto0804** [comment]
> the input is still a given layout, isn't it?

Yes, but if you put some random numbers in the position part and choose `cond=c`, it will be equivalent to what you want.

Directly instantiating the variables is straightforward but might be prone to make errors. If you choose to do that, please be careful with the correspondence between the sequence ids and layout attributes.

**Comment by Lanjiong-Li** [comment]
Thanks a lot !
I still got one more question about choosing the best layout.Since I can choose the number of samples to generate once a time, if I understand correctly, I can use my trained fid_model to evaluate the samples I generate and select the one with highest score right?
And do you have any suggestion to get the best layout?Can I just simply generate as many as possible and use fid_model to score them?
