### ISSUE TITLE
Baseline code?

### ISSUE THREAD

**Issue by billy322** [CyberAgentAILab/layout-dm#26]
Can you tell me where to find the code for the baselines mentioned in your paper? e.g., BART, MaskGIT, NDN-none, VQDiffusion.

Thanks.

**Comment by naoto0804** [comment]
Please refer to [models](https://github.com/CyberAgentAILab/layout-dm/tree/main/src/trainer/trainer/models).
We implemented NDN-none on another codebase, so it is not included here.

For training each model with the default hyper-parameters, please refer to [here](https://github.com/CyberAgentAILab/layout-dm#training).

**Comment by kitman0000** [comment]
May I also have the NDN-none code base? thanks!
