### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by arnoldmr01** [CyberAgentAILab/layout-dm#28]
I am so grateful for your work on LayoutDM. The concept behind LayoutDM is both interesting and compelling. Recently, I would like to apply LayoutDM to my project of generating advertisement images. Is the raw data (Json file) necessary? Where is the code for forward diffusion process? If you have any suggestion please let me know.

Warm regards, 
Arnold

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our work!

> Is the raw data (Json file) necessary?

The answer is no, as long as you can preprocess your data on your own.
Please refer to [Training on custom dataset](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md) for more details.

> Where is the code for the forward diffusion process?

Please refer to [This file](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/models/categorical_diffusion/base.py)

**Comment by arnoldmr01** [comment]
Thanks for you response. It did help me a lot.
