### ISSUE TITLE
Testing on my own set of bounding boxes

### ISSUE THREAD

**Issue by Ashwin-Pokharel** [CyberAgentAILab/layout-dm#3]
Hey , if i have my own set of bounding boxes how can i generate the dataset needed for testing. Would i have to create my own dataset class that mirrors the one being used by publaynet?

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our repo.
The answer is generally yes. Please refer to [a guide for custom dataset generation](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md).

If you just want to test some own-made PubLayNet-like layouts quickly, another option might be to initialize a [Batch](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.data.Batch.html) instance directly. This instance is usually sampled from the dataset or dataloader instance in our framework, but it is possible to make it on your own.

**Comment by Ashwin-Pokharel** [comment]
oh thats perfect yea i will utilize the batch instance. i just wanted to still use the weights from publaynet but be able to apply it to my own custom bounding boxes.  If you have any further suggestions for that please let me know.

**Comment by Ashwin-Pokharel** [comment]
Also one last thing , if i wanted to for example figure out what a resized layout might look like , how would i let the model predict only w , h or some other pieces

**Comment by naoto0804** [comment]
> how would i let the model predict only w , h or some other pieces

We've defined some common usecases as "task" [here](https://github.com/CyberAgentAILab/layout-dm/blob/e107db0a84ed83876ecfd257149a99229f662176/src/trainer/trainer/helpers/task.py#L16-L24). If these cases do not meet your requirements, then you can define your task and implement [get_cond](https://github.com/CyberAgentAILab/layout-dm/blob/e107db0a84ed83876ecfd257149a99229f662176/src/trainer/trainer/helpers/task.py#L94-L106) for that task by hiding all the fields that you want to predict.

**Comment by naoto0804** [comment]
> If you have any further suggestions for that please let me know.

I'll make a small example to instantiate a Batch instance later since some other people might ask similar kinds of things.
However, I'm busy in this and next week so I'm not sure when I can do it.

**Comment by Ashwin-Pokharel** [comment]
thank you so much , i was able to accomplish it by creating my own dataset and following most of the steps of the configuring custom dataset. Just had to remember pass in the  custom dataset with the taget index during prediction.

**Comment by Ashwin-Pokharel** [comment]
sorry to reopen the issue thread but I had one last question , can these tasks take into account differing canvas sizes?

**Comment by naoto0804** [comment]
No problem. Current layout generation approaches, including ours, cannot consider different canvas sizes since they do not feed the canvas size information to their model. We may provide some signals to consider the canvas sizes by logit adjustment during the iterative prediction of LayoutDM in principle, but I haven't tested it yet. It is the next challenge that the community should tackle.

**Comment by Ashwin-Pokharel** [comment]
ahh ok thank you!
