### ISSUE TITLE
Test on my own data

### ISSUE THREAD

**Issue by Brembles** [CyberAgentAILab/layout-dm#30]
How should I construct the data set if I want to test other images?

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our repo!
Please refer to [here](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md) first, and I'm happy to answer additional questions!

**Comment by naoto0804** [comment]
Feel free to reopen if you wanna ask more!
