### ISSUE TITLE
Some questions about trainer for a beginner

### ISSUE THREAD

**Issue by NurseryRhymeA** [CyberAgentAILab/layout-dm#31]
Hi,I would like to run your code on my computer. I am using the Windows platform, and I have successfully installed the required dependencies. However, I am facing some issues with the 'trainer' module and I am hoping to receive your guidance to resolve them. 
When I run the code, I'm getting errors in parts where references like 'target: trainer.models.layoutdm.LayoutDM' and 'from trainer' are used. The 'trainer' folder is located under 'src/trainer/'. So, I'm curious why I don't need to use absolute or relative paths to reference them. Is this a feature of Hydra or Poetry?Or could it be a difference between Linux and Windows platforms?

![20231221170822](https://github.com/CyberAgentAILab/layout-dm/assets/80157816/af5ff3de-37cc-462b-a199-fe0ffa84419e)

  As a beginner who has recently started delving into these topics, I apologize if my question seems naive or silly. Nevertheless, it has been bothering me for quite some time, and I would greatly appreciate your assistance and insights. Thank you very much in advance.

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our repo and for reporting many details, which helped me identify the problem faster!

I suspect the dependencies are not properly installed, did you make your env. by conda? Could you check and print the result of the following command?
```
$ poetry run which python
$ poetry run python -m pip freeze | grep trainer
```

> I'm curious why I don't need to use absolute or relative paths to reference them

If one successfully installs the dependencies, `trainer` is installed as a package (see [packages](https://python-poetry.org/docs/pyproject/#packages) features in poetry and [how we specify in pyproject.toml](https://python-poetry.org/docs/pyproject/#packages)). As you may know, packaging alleviates some troubles regarding absolute/relative import in Python (see [Python Packaging User Guide](https://packaging.python.org/en/latest/)).

**Comment by PhucHau0312** [comment]
Could we train layoutdm on only one of the condition tasks like: c->p+s, c+s->p, refinement, ...., couldn't we ?

**Comment by naoto0804** [comment]
@PhucHau0312 Yes, it is possible by keeping the conditional information fixed throughout the forward / reverse process.

**Comment by PhucHau0312** [comment]
> @PhucHau0312 Yes, it is possible by keeping the conditional information fixed throughout the forward / reverse process.

Thank you. I have one more question that loss of layoutdm combines all condition tasks, right ?

**Comment by naoto0804** [comment]
> loss of layoutdm combines all condition tasks, right ?

If you optimize the model for a pre-defined set of conditional tasks, the answer is yes.

**Comment by PhucHau0312** [comment]
> keeping the conditional information fixed throughout the forward / reverse process.

@naoto0804 I didn't see the conditional information argument throughout the training process. Could you show me ?

**Comment by NurseryRhymeA** [comment]
> Hi, thank you for your interest in our repo and for reporting many details, which helped me identify the problem faster!
> 
> I suspect the dependencies are not properly installed, did you make your env. by conda? Could you check and print the result of the following command?
> 
> ```
> $ poetry run which python
> $ poetry run python -m pip freeze | grep trainer
> ```
> 
> > I'm curious why I don't need to use absolute or relative paths to reference them
> 
> If one successfully installs the dependencies, `trainer` is installed as a package (see [packages](https://python-poetry.org/docs/pyproject/#packages) features in poetry and [how we specify in pyproject.toml](https://python-poetry.org/docs/pyproject/#packages)). As you may know, packaging alleviates some troubles regarding absolute/relative import in Python (see [Python Packaging User Guide](https://packaging.python.org/en/latest/)).

I sincerely appreciate your response. Over the past few days, I installed Ubuntu and made attempts on it. Although the installation of Poetry failed due to my installation of Anaconda, fortunately, this may have helped me identify the issue. I suspect it is a path problem caused by Anaconda, as there were error messages related to it. Even after uninstalling Anaconda, I still encounter related path issues.I will continue my attempts to resolve it. 
Your answer has been of tremendous help to me as a beginner. I don't know how to express my gratitude, but thank you very much.

**Comment by sevenotes** [comment]
> > keeping the conditional information fixed throughout the forward / reverse process.
> 
> @naoto0804 I didn't see the conditional information argument throughout the training process. Could you show me ?

I am sorry , but I am still attempting to run it.

**Comment by naoto0804** [comment]
Feel free to re-open!
