### ISSUE TITLE
about the layoutDM+ in paper "Retrieval-Augmented Layout Transformer for Content-Aware Layout Generation"

### ISSUE THREAD

**Issue by Usernamezhx** [CyberAgentAILab/layout-dm#32]
Thank you for your contribution to the layout work. I read the paper "Retrieval-Augmented Layout Transformer".  it point that:
`LayoutDM† [19] is a discrete state-space diffusion model that can handle many constrained generation tasks. Since the model is originally designed for content-agnostic layout generation, we extend the model to accept an input image.`
Can you provide some ideas about the layoutDM+. thanks very much.

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our projects!

LayoutDM+ inserts the cross-attention layer (typical one in Transformer decoder) into [the building block](https://github.com/CyberAgentAILab/layout-dm/blob/873b5eebe4c61862e5c08a10859accf65a168dfd/src/trainer/trainer/models/transformer_utils.py#L103) to attend flattened image feature maps.

**Comment by Usernamezhx** [comment]
thanks for your reply.
