### ISSUE TITLE
Overlap Metrics 

### ISSUE THREAD

**Issue by billy322** [CyberAgentAILab/layout-dm#33]
Hi, for the Overlap metrics, you are using the LayoutGAN++ metrics, but the Overlap in the LayoutGAN++ paper fall into a scale between 0-1000? E.g., 188.77±0.93 and 32.40±0.89 in Table 3 in the LayoutGAN++ paper [1]. Can I know how to convert to that scale for reporting? Thanks.

[1] https://dl.acm.org/doi/pdf/10.1145/3474085.3475497

**Comment by naoto0804** [comment]
Hi, according to the paper, the multiplication factor is as follows.
- LayoutGAN++: Alignment and Overlap are multiplied by 100× for visibility (mentioned in Table 3)
- LayoutDM: only Alignment is multiplied by 100× for visibility (mentioned in B.5 of appendix)
