### ISSUE TITLE
ETA for train fid model

### ISSUE THREAD

**Issue by hengrui0516** [CyberAgentAILab/layout-dm#35]
First thank for your wonderful work!
Today I want to train a fid model for my own dataset which contains only 300 layouts using a single GPU.
But I roughly estimate that it will take 27 days to train, and I wonder whether it's normal.

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our project!

27 days seems strange unless you are using GPUs... Anyway, you can take your own risk and stop the training if the loss does not go down and the validation results (e.g., [saved images](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/fid/train.py#L166-L181)) looks OK.

**Comment by naoto0804** [comment]
Feel free to re-open if you have more questions!
