### ISSUE TITLE
layoutgan++ baseline problem

### ISSUE THREAD

**Issue by deadsmither5** [CyberAgentAILab/layout-dm#36]
hi , sorry to bother you, I‘m wondering the layoutgan++ which you compared with layoutdm in your paper is the constraint one or the normal one, and could you please tell me the generator and discriminator's hyper parameters? whether you both set the dimfeed = 2048 and dmodel =512 in layoutgan++'s G and D? waiting for your answer,thank you!

**Comment by naoto0804** [comment]
> whether you both set the dimfeed = 2048 and dmodel =512 in layoutgan++'s G and D?

As far as I remember, I did that for its fair comparison.

> constraint or normal

I used constraint ver. for the relationship task and normal ver. otherwise.

**Comment by deadsmither5** [comment]
thank you!
