### ISSUE TITLE
Question about the metrics

### ISSUE THREAD

**Issue by hengrui0516** [CyberAgentAILab/layout-dm#37]
Hi, thanks for your excellent work!
I notice that eval.py will get various results for a single metric, such as: 
        overlap-ACLayoutGAN: 1.1473 (0.0000%)
        overlap-LayoutGAN: 0.0554 (0.0000%)
        overlap-LayoutGAN++: 0.1914 (0.0000%)
I wonder which one is used in the maintext of the CVPR paper.

**Comment by naoto0804** [comment]
Thank you for your interest in our work!

Please refer to #23.

Feel free to re-open if you have more questions!
