### ISSUE TITLE
Demo about how to output layout generation results under given partial category constraints

### ISSUE THREAD

**Issue by liuan0803** [CyberAgentAILab/layout-dm#38]
Hello, thank you for your excellent work. I have a question. If I want to specify some category constraints: it must contain 3 categories 1 and 2 categories 2. Then output the layout results. I would like to ask if you can give me a demo example for testing? grateful.

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our project! Please refer to [here](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/helpers/task.py#L94-L110), since your setting is equal to `cond_type = "c"`.

**Comment by naoto0804** [comment]
Closed due to inactivity. Feel free to re-open if you have more questions!
