### ISSUE TITLE
Hardware requirement

### ISSUE THREAD

**Issue by hsinwu13** [CyberAgentAILab/layout-dm#40]
![image](https://github.com/CyberAgentAILab/layout-dm/assets/78135649/a2aa20ed-e87e-4048-9e8a-ee3119d7d00c)

 I would like to ask the hardware requirement for the training? Thank you.

**Comment by hsinwu13** [comment]
and I would like to ask the hardware requirement for the training? Thank you.

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our project! I was working on T4 (16GB), so it should work. Do you work on a custom dataset?

**Comment by naoto0804** [comment]
Closed due to inactivity. Feel free to re-open if you have more questions!
