### ISSUE TITLE
Error in model initialization

### ISSUE THREAD

**Issue by dips4717** [CyberAgentAILab/layout-dm#42]
Hi @naoto0804 ,

I am trying to install the repo various ways into a docker container. 
I have managed to install all the requirement.

While running the notebooks/demo.ipynb on the line 

`model = instantiate(train_cfg.model)(
    backbone_cfg=train_cfg.backbone, tokenizer=tokenizer
).to(device)`

I get following error 

![image](https://github.com/user-attachments/assets/853f727d-0c6c-4ca0-a082-f6ab44e9d1a8)

Surely I can see the keyword argument in the Block class but not sure why this throws an error. It is related to hydra or the trainer module itself? Any suggestion.

**Comment by dips4717** [comment]
Resolved with pytorch upgrade to 1.10. Thanks.

**Comment by naoto0804** [comment]
Thank you for your interest in our repo, and I'm glad that you have solved the error!
