### ISSUE TITLE
Can I use this for widgets, or does it only work with website layouts?

### ISSUE THREAD

**Issue by andupotorac** [CyberAgentAILab/layout-dm#43]
This isn't clear to me from the demo. I want to be able to tell it to generate video players for example, and for it to be able to do so randomly.

**Comment by naoto0804** [comment]
Hi, thank you for your interest in our repo! It is possible in principle. For experiments, we tested the [Rico](http://www.interactionmining.org/rico.html) dataset, which consists of wireframes for mobile app UIs.

**Comment by andupotorac** [comment]
Thanks, will try it out at some point! :)
